# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'Group01Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 4.5'
	pod 'RAMAnimatedTabBarController'
	pod 'ObjectMapper', '~> 3.3'
	pod 'AlamofireObjectMapper', '~> 5.0'
	pod 'RealmSwift', '3.16.2'
	pod 'RxSwift',    '~> 4.0'
	pod 'RxCocoa',    '~> 4.0'
	pod 'RxRealm'
	pod 'Kingfisher', '~> 4.0'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Charts'
	pod 'DropDown'
  # Pods for Group01Project

end
